DROP TABLE IF EXISTS paciente;

CREATE TABLE IF NOT EXISTS paciente (
	codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL,
	sexo CHAR(1) NOT NULL,
	idade INT NOT NULL,	
	logradouro VARCHAR(30),
	numero VARCHAR(30),
	complemento VARCHAR(30),
	bairro VARCHAR(30),
	cep VARCHAR(30),
	cidade VARCHAR(30),
	estado VARCHAR(30),
	celular VARCHAR(15) NOT NULL,
	plano INT NOT NULL,
	servico INT NOT NULL
);


DROP TABLE IF EXISTS plano;

CREATE TABLE IF NOT EXISTS plano (
	codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL
);


DROP TABLE IF EXISTS servico;

CREATE TABLE IF NOT EXISTS servico (
	codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nome VARCHAR(50) NOT NULL
);


DROP TABLE IF EXISTS planoservico;

CREATE TABLE IF NOT EXISTS planoservico (
	codigo INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	plano INT NOT NULL,
	servico INT NOT NULL
);
